In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels as sm
from datetime import datetime, date, time

In [31]:
# Object is not copied but referred -> Pass by reference

a = [1,2,3]
b = a
print(b)
a.append(4)
print(a)
print(b)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [52]:
# primdata type is copied -> Pass by value
a = 3
b = a
print(b)
a = 4
print(a)
print(b)

3
4
3


In [53]:
#Using ? and ??

def add_numbers(a, b):
    """
    Add two numbers together
    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

# add_numbers?
# add_numbers??

In [54]:
# a + b Add a and b
# a - b Subtract b from a
# a * b Multiply a by b
# a / b Divide a by b
# a // b Floor-divide a by b, dropping any fractional remainder
# a ** b Raise a to the b power
# a & b True if both a and b are True; for integers, take the bitwise AND
# a | b True if either a or b is True; for integers, take the bitwise OR
# a ^ b For booleans, True if a or b is True, but not both; for integers, take the bitwise EXCLUSIVE-OR
# a == b True if a equals b
# a != b True if a is not equal to b
# a <= b, a < b True if a is less than (less than or equal) to b
# a > b, a >= b True if a is greater than (greater than or equal) to b
# a is b True if a and b reference the same Python object
# a is not b True if a and b reference different Python objects

In [61]:
# objects in Python, such as lists, dicts, NumPy arrays, and most user-defined types (classes), are mutable
# strings and tuples, are immutable:
a_tuple = (3, 5, (4, 5), "four")
# a_tuple[1] = 'four'


In [5]:
s = 'python'
print(s[3])

#######################

s = 'python'
print(s[:3])
#######################

s = '12\34'
print(s)

#######################

s = '12\\34'
print(s)

#####################

template = '{0:.2f} {1:s} are worth US${2:d}'
temp1 = template.format(4.5560, 'Argentine Pesos', 1)

print(template)
print(temp1)

h
pyt
12
12\34
{0:.2f} {1:s} are worth US${2:d}
4.56 Argentine Pesos are worth US$1


In [78]:
# # Date time


# %m Two-digit month [01, 12]
# %d Two-digit day [01, 31]
# %H Hour (24-hour clock) [00, 23]
# %I Hour (12-hour clock) [01, 12]
# %M Two-digit minute [00, 59]
# %S Second [00, 61] (seconds 60, 61 account for leap seconds)
# %w Weekday as integer [0 (Sunday), 6]
# %U Week number of the year [00, 53]; Sunday is considered the first day of the week, and days before the first Sunday of
# the year are “week 0”
# %W Week number of the year [00, 53]; Monday is considered the first day of the week, and days before the first Monday of
# the year are “week 0”
# %z UTC time zone offset as +HHMM or -HHMM; empty if time zone naive
# %F Shortcut for %Y-%m-%d (e.g., 2012-4-18)
# %D Shortcut for %m/%d/%y (e.g., 04/18/12)

In [47]:
import datetime as dt

date = dt.datetime.now()
print(date.strftime('%F'))

date1 = dt.datetime(2020,10,31,23,10,00)
print(date1.strftime("%D"))

2020-03-26
10/31/20


In [91]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [93]:
for a, b, c in seq:
    print('a={2}, b={1}, c={0}'.format(a, b, c))  

a=3, b=2, c=1
a=6, b=5, c=4
a=9, b=8, c=7


In [48]:
# Used to access index

some_list = ['foo', 'bar', 'baz']
mapping = {}
for i, v in enumerate(some_list):
    print(v)
    print(i)
    mapping[i] = v

mapping

foo
0
bar
1
baz
2


{0: 'foo', 1: 'bar', 2: 'baz'}

In [99]:
# Set, list, tuple and dictionary --> Python
# Series, dataframe --> Numpy and pandas. Numpy and pandas are libraries used for DS and were written in C which makes them 
# very fast in operations

# Eg.

list_a = [1,2,3,4,1,2,3] # duplicates can be stored
set_a = set([5,4,1,2,3,4,1,2,3]) # will not store duplicate values
tuple_a = (1,2,3,4,1,2,3) # Immutable ; values cannot be added nor changed
dict_a = {"a":"value1", "b":3}
set_b = set({"a", "b", "a","c"})

print(list_a[0])
print(set_a)
print(dict_a["a"])
print(tuple_a[1])
print(set_b)

1
{1, 2, 3, 4, 5}
value1
2
{'c', 'a', 'b'}


In [57]:
set_b = set(list_a)
list_b = list(set_b)

print(set_b)
print(list_b)

{1, 2, 3, 4}
[1, 2, 3, 4]


# For Loops

In [111]:
for i in range(5,10):
    print(i)

print("=================")


for i in range(10,3,-1):
    print(i)

print("=================")


list_a = ["neha", "parekh", "mehul"]    
for index, value in enumerate(list_a):
    print(index)
    print(value)


5
6
7
8
9
10
9
8
7
6
5
4
0
neha
1
parekh
2
mehul


# Functions

In [64]:
def my_fun(x):
    return x*x;
    
a = my_fun(100) 
print(a)

10000


In [67]:
equiv_anon = lambda x: x * x

a = equiv_anon(100)
print(a)


10000


In [75]:
list_a = [1,2,3,4,5,6]
list_b = []
lamb_fun = lambda x: x*x

for i in range(0,6,1):
    b = lamb_fun(list_a[i])
    list_b.append(b)

print(list_b)

[1, 4, 9, 16, 25, 36]


# NumPy

In [71]:
import numpy as np

In [72]:
arr = np.array([1,2,3,4])

In [125]:
arr1 = np.zeros((2,3))
print(arr1)


print("=================")


arr2 = np.ones_like(arr1)
print(arr2)


print("=================")


arr3 = np.empty((2,3,3))
arr3[1,2,2] = 10
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0. 10.]]]


In [36]:
lis = [1,1,3,4]

lis.append(4)

if 5 in lis:
    print("yes")


In [37]:
lis

[1, 1, 3, 4, 4]

In [18]:


set_a = set((1,2,3))
set_a.add(4)
set_a
set_a.remove(2)
set_a

if 3 in set_a:
    print("yes")

yes


In [23]:
for index, ele in enumerate(lis):
    print(index," ", ele)

0   1
1   1
2   3
3   4
4   4


In [58]:
map_a = {1:"2",2:"4",3:"6",4:"10"}

print(map_a)

for ele in map_a:
    print(map_a[ele])
    
if 3 in map_a:
    print("yes")
    
del map_a[2]

map_a

{1: '2', 2: '4', 3: '6', 4: '10'}
2
4
6
10
yes


{1: '2', 3: '6', 4: '10'}

In [38]:
lis_2 = [i+1 for i in lis]

[1, 1, 3, 4, 4]

In [59]:
map_b = sorted(map_a.values(), key = lambda a : -int(a) )


In [60]:
map_b

['10', '6', '2']

### Indexing in Python

In [3]:
date_index = pd.date_range('20200402', periods=6)

In [7]:
dataframe_1 = pd.DataFrame(np.random.rand(6,4), columns= list('ABCD'), index = date_index)

In [8]:
np.array([3]*4, dtype = float)

array([3., 3., 3., 3.])

In [49]:
index_df2 = pd.date_range('20200401', '2020-04-04', periods = 4)

index_df2

DatetimeIndex(['2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04'], dtype='datetime64[ns]', freq=None)

In [62]:
df_2  = pd.DataFrame({'A': np.array([1.0]*4, dtype = float),
                     'B':pd.Categorical(['test','train','train','test']),
                     'C':pd.Timestamp('20200401'),
                     'D': 1.0,
                     'E':'foo',
                     'F': 3,
                     'G':[1,3,4,5]}, index = index_df2)

df_2

A      B          C    D    E  F  G
2020-04-01  1.0   test 2020-04-01  1.0  foo  3  1
2020-04-02  1.0  train 2020-04-01  1.0  foo  3  3
2020-04-03  1.0  train 2020-04-01  1.0  foo  3  4
2020-04-04  1.0   test 2020-04-01  1.0  foo  3  5

In [63]:
df_2.dtypes

A           float64
B          category
C    datetime64[ns]
D           float64
E            object
F             int64
G             int64
dtype: object

In [64]:
df_2.columns.values

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype=object)

In [65]:
df_2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')

In [66]:
df_2.index

DatetimeIndex(['2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04'], dtype='datetime64[ns]', freq=None)

In [67]:
df_2.to_numpy()

array([[1.0, 'test', Timestamp('2020-04-01 00:00:00'), 1.0, 'foo', 3, 1],
       [1.0, 'train', Timestamp('2020-04-01 00:00:00'), 1.0, 'foo', 3, 3],
       [1.0, 'train', Timestamp('2020-04-01 00:00:00'), 1.0, 'foo', 3, 4],
       [1.0, 'test', Timestamp('2020-04-01 00:00:00'), 1.0, 'foo', 3, 5]],
      dtype=object)

In [72]:
df_2.sort_index(axis = 1, ascending = False)

G  F    E    D          C      B    A
2020-04-01  1  3  foo  1.0 2020-04-01   test  1.0
2020-04-02  3  3  foo  1.0 2020-04-01  train  1.0
2020-04-03  4  3  foo  1.0 2020-04-01  train  1.0
2020-04-04  5  3  foo  1.0 2020-04-01   test  1.0

In [70]:
df_2.sort_values(by='G')

A      B          C    D    E  F  G
2020-04-01  1.0   test 2020-04-01  1.0  foo  3  1
2020-04-02  1.0  train 2020-04-01  1.0  foo  3  3
2020-04-03  1.0  train 2020-04-01  1.0  foo  3  4
2020-04-04  1.0   test 2020-04-01  1.0  foo  3  5

### Accessing Values

In [85]:
df_2.iloc[:-1, :-1]

A      B          C    D    E  F
2020-04-01  1.0   test 2020-04-01  1.0  foo  3
2020-04-02  1.0  train 2020-04-01  1.0  foo  3
2020-04-03  1.0  train 2020-04-01  1.0  foo  3

In [89]:
df_2.iloc[:-1, [df_2.columns.get_loc('A'), df_2.columns.get_loc('B')]]

A      B
2020-04-01  1.0   test
2020-04-02  1.0  train
2020-04-03  1.0  train

In [92]:
#df_2.iloc[:-1, df_2.columns.get_loc(['A', 'B'])]

df_2.iloc[:-1, [df_2.columns.get_loc(col) for col in ['A', 'B']]]


A      B
2020-04-01  1.0   test
2020-04-02  1.0  train
2020-04-03  1.0  train

In [114]:

df_2[df_2['B'].isin(['test'])]

df_2[df_2['G']>2]

A      B          C    D    E  F  G
2020-04-02  1.0  train 2020-04-01  1.0  foo  3  3
2020-04-03  1.0  train 2020-04-01  1.0  foo  3  4
2020-04-04  1.0   test 2020-04-01  1.0  foo  3  5

In [115]:
s1 = pd.Series([1,2,3,4,5,6,6], index = pd.date_range('20200401', periods = 7))

In [121]:
df2 = df_2.copy()

In [131]:
df3 = df2.reset_index()

In [139]:
df3

index    A      B          C    D    E  F  G
0 2020-04-01  1.0   test 2020-04-01  1.0  foo  3  1
1 2020-04-02  1.0  train 2020-04-01  1.0  foo  3  3
2 2020-04-03  1.0  train 2020-04-01  1.0  foo  3  4
3 2020-04-04  1.0   test 2020-04-01  1.0  foo  3  5

In [140]:
x1 = np.linspace(0, 5)

In [141]:
x1

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

### Categorical Data

In [3]:
df = pd.DataFrame({"id": [1, 2, 3, 4, 5, 6], "raw_grade": ['a', 'b', 'b', 'a', 'a', 'e']})

In [5]:
df["grade"] = df["raw_grade"].astype("category")

In [7]:
df["grade"].cat.categories = ["very good", "good", "very bad"]
df

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [8]:
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])
df

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad


# PySpark

In [11]:
from pyspark.sql import SparkSession